### ISSUE TITLE
More info on dealing with JSON/GeoJSON in python and R

### ISSUE THREAD

**Issue by HughSt** [disarm-platform/docs#1]
Would be good to provide R and python specific documentation on the approach we’ve taken getting data in/out of functions. I.e. in R we use fromJSON(readLines()) which results in a list. Similarly, it would be useful to outline how we deal with GeoJSON in both languages.

**Comment by onlyjsmith** [comment]
@HughSt checking that this is part-covered by your `creating_in_R.md` file?

**Comment by HughSt** [comment]
Yes exactly. Do we have a python version of this yet?

**Comment by HughSt** [comment]
Closing as we now have python version
