### ISSUE TITLE
Problem with copying code

### ISSUE THREAD

**Issue by HughSt** [disarm-platform/docs#10]
If I use the copy functionality to copy the CURL request, when I paste into the terminal it seems to end up on multiple lines and doesn't work

**Comment by onlyjsmith** [comment]
Part of the problem might have been that the commands often have a `$` at the start: we included to make it clear you enter the command at the command line (not in R or Python, etc), but you should not include the actual `$` itself. When you click copy, it includes the `$` and so doesn't work. I've removed all I could find (they were only on https://docs.disarm.io/api-docs/testing-and-debugging-functions/running-deployed-functions-for-development-and-testing)

Are there some other examples that still don't work, separate to anything discussed in #11?

**Comment by HughSt** [comment]
Think this is wrapped up in #11. i.e. it doesn't work for any multi-line snippets

**Comment by onlyjsmith** [comment]
Closing for #11
