### ISSUE TITLE
CURL requests docs

### ISSUE THREAD

**Issue by HughSt** [disarm-platform/docs#11]
In the page [running-deployed-functions-for-development-and-testing](https://docs.disarm.io/api-docs/testing-and-debugging-functions/running-deployed-functions-for-development-and-testing), In addition to issue #10 there seem to be errors in the CURL request documentation. 

```
curl -X POST https://faas.srv.disarm.io/function/longrun
{"function_status":"error","result":{"message":"Required param missing: 'delay_s'"}}
```

The next example with a single parameter seems to have some erroneous " marks
```
curl -X POST" "https://faas.srv.disarm.io/function/longrun" \
    -H 'Content-Type: application/json' \
    -d '{"delay_s": 0.5}'
```

I think it should be 

```
curl -X POST https://faas.srv.disarm.io/function/longrun \
    -H 'Content-Type: application/json' \
    -d '{"delay_s": 0.5}'
```
But this returns the following success with error/warning message:
```
{"function_status":"success","result":{"count":1378491,"params":{"delay_s":0.5},"status":"done after 0.5 seconds"}}
curl: (3) URL using bad/illegal format or missing URL
```

And the third example which uses a local JSON file, I can't work out how to include the directory to the file. For example, if I cd to the fn-raster-vector-summary-stats/function and run
```
curl -X POST https://faas.srv.disarm.io/function/longrun \ --data-binary @test_req.json
```
or
```
curl -X POST https://faas.srv.disarm.io/function/longrun \ --data-binary '@test_req.json'
```

I get the following:
```
{"function_status":"error","result":{"message":"Required param missing: 'delay_s'"}}
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: test_req.json
```

Could the PPLS team take a look? Cheers

**Comment by HughSt** [comment]
Also, the httpie example is returning errors

```
http POST https://faas.srv.disarm.io/function/longrun \ 'Content-Type':'application/json' \ delay_s:=0.5
```

```
http: error: ValueError: Invalid header name b' Content-Type'
```

**Comment by onlyjsmith** [comment]
I've changed the 'simplest' one to include the `delay_s` param, so it returns success.

The second had an extra `"` next to `POST`, but the quotes around the URL are optional.

The other issues might be related to a copy-paste issue around the `\` character. This character is used to enter multi-line commands into the terminal. So you can either remove the `\` when you copy and paste it as a single long command, or keep it and make sure there are line breaks after each of them.

For example: 
- BREAKS: `http POST https://faas.srv.disarm.io/function/longrun \ delay_s:=0.5`
- WORKS: `http POST https://faas.srv.disarm.io/function/longrun delay_s:=0.5`

**Comment by HughSt** [comment]
Great thanks - looks like the first change to the simplest CURL request has yet to make it to the live master site.

For the second issue with the `\` character - are you happy that users will know that the copy/paste functionality won't work for multiline snippets?

**Comment by onlyjsmith** [comment]
Ah! I'm only looking at `httpie` one - didn't remember we also had the `curl` versions - have updated that one too. I've realised that we now have a duplicate request for each - they both had another request that included the `delay_s` param. So I've removed the 'simplest' request from each.

For the `\` character - as long as you copy-and-paste straight into the terminal, the slash should work fine. I've tried a few examples with no problems. Can you make a little video of what you're doing? (Btw, CMD+SHIFT+5 on mac can help with that)

**Comment by onlyjsmith** [comment]
@HughSt can you re-open if you hit this copy-paste issue again?
