### ISSUE TITLE
Broken link in troubleshooting

### ISSUE THREAD

**Issue by HughSt** [disarm-platform/docs#15]
The link to 'testing functions locally' is broken on [this](https://docs.disarm.io/api-docs/testing-and-debugging-functions/troubleshooting-functions) page. Related to #8

**Comment by onlyjsmith** [comment]
Link fixed on https://docs.disarm.io/api-docs/testing-and-debugging-functions/troubleshooting-functions. Points to https://docs.disarm.io/api-docs/testing-and-debugging-functions/testing-local-function-containers
