### ISSUE TITLE
More info on editing stack.yml

### ISSUE THREAD

**Issue by HughSt** [disarm-platform/docs#2]
Thanks for the additional section on editing stack.yml. We have to remember that the audience for this is modelers who are likely to not have any familiarity with docker/containers and this sort of thing. We need to do a bit more hand holding. Would be great if you could think through the following

1. Can we add some more background on what the stack.yml is actually doing. 
2. Its worth noting that the indentations are meaningful (I think?) and that various lines are just headers (e.g. `Provider`, `Function` etc.)
3. A screenshot of an example stack.yml filled in. Something like 'For example, if we have a function called x, and are deploying to our OpenFaas gateway called y, your stack.yml would look like this...
4. Can we add more information on each section. For example `lang` how would I know what to write here? We give an example of `Dockerfile` but what are the other options and when would I need them, if ever?

**Comment by onlyjsmith** [comment]
@TNgidi I've edited on `develop`: https://disarm.gitbook.io/disarm-docs-staging/v/develop/api-docs/creating-and-deploying-functions/editing-stack-yml

**Comment by TNgidi** [comment]
I have reviewed and looks good

**Comment by HughSt** [comment]
Thanks guys
