### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by HughSt** [disarm-platform/docs#3]
Would be good to add some more background/rationale on why versioning is a good idea and how it is possible to use different versions etc.

**Comment by onlyjsmith** [comment]
Edited. @TNgidi pls review https://disarm.gitbook.io/disarm-docs-staging/v/develop/api-docs/creating-and-deploying-functions/versioning-algos

**Comment by TNgidi** [comment]
I've checked this one, it makes sense to me

**Comment by HughSt** [comment]
Thanks, looks great
