### ISSUE TITLE
Testing local function containers

### ISSUE THREAD

**Issue by HughSt** [disarm-platform/docs#4]
Step 6 is incomplete

**Comment by onlyjsmith** [comment]
Fixed?

<img width="672" alt="Screenshot 2019-10-23 09 07 53" src="https://user-images.githubusercontent.com/148280/67366877-9ff29f00-f574-11e9-8a17-c56ff131e9e2.png">

**Comment by onlyjsmith** [comment]
Have edited. Check staging: https://disarm.gitbook.io/disarm-docs-staging/v/develop/api-docs/testing-and-debugging-functions/testing-local-function-containers

@TNgidi can you review?

**Comment by TNgidi** [comment]
Reviewed and looks good.
