### ISSUE TITLE
change 'creation' to use templates

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/docs#5]

**Comment by onlyjsmith** [comment]
@TNgidi i've edited https://disarm.gitbook.io/disarm-docs-staging/v/develop/api-docs/creating-and-deploying-functions/creating

**Comment by TNgidi** [comment]
I've reviewed and looks good. I was wondering if it make sense to show one template (screenshot)?

**Comment by onlyjsmith** [comment]
:-) what does a template look like?! 

You mean like a folder outline? That could work. Want to try making one?

**Comment by TNgidi** [comment]
Yes, just to get a better idea of what the stuff that is ready to build into an image will look like as we are packaging the function in this section.
I will try and make one

**Comment by onlyjsmith** [comment]
How about a text-version:

```
new-function-py
├── handler.py
├── preprocess_params.py
└── requirements.txt
```

and 

```
new-function-r
├── function.R
├── install_packages.R
├── preprocess_params.R
├── test_req.json
└── utils.R
```

(Looking at it this way, I think the R template might have a few too many files included)

**Comment by onlyjsmith** [comment]
I've added this in and pushed, same link as above. @TNgidi what do you think?

**Comment by TNgidi** [comment]
That would be a good idea. It answers the question I would have about the files required to build the function into an image.

**Comment by HughSt** [comment]
This looks good, although one question which we may have already hashed out. Should we call the python files by the same names as the R files, i.e. change `index.py` to `main.py` (or vice versa) and similarly for `requirements.txt` and `install_packages.r`?

**Comment by onlyjsmith** [comment]
@HughSt that's certainly more consistent and _might_ keep us saner, but I'd suggest keeping it a lower-priority issue: there are lots of differences between the different languages already, and renaming the files to be similar (but not the same), might actually make it easier to make silly mistakes. Plus, e.g. `requirements.txt` is a Python standard that is just a text file list of packages, while our `install_packages.R` file contains code that is executed during the build.

Suggest no action.

**Comment by HughSt** [comment]
Roger.
