### ISSUE TITLE
minor typo in scaffolding

### ISSUE THREAD

**Issue by HughSt** [disarm-platform/docs#7]
On the image for the r function directory the folder name should be `r-new-function` instead of `py-new-function`

**Comment by onlyjsmith** [comment]
Fixed in https://github.com/disarm-platform/docs/commit/eb62fe4108ab6c8b0cce659e36d6c2016033b1bb (thought that commit seems to include a lot of unrelated auto-formatting type of changes which I didn't deliberately do!)

**Comment by onlyjsmith** [comment]
Btw @HughSt in case you see something similar, the 'image' is just text, so you should be able to edit it via gitbook.com or github.com etc.
