### ISSUE TITLE
Testing functions docs

### ISSUE THREAD

**Issue by HughSt** [disarm-platform/docs#8]
Hi all,

We provide some guidance in the docs on how to test the _function_ (as opposed to the container) locally, e.g. 

`echo test_req.json | Rscript main.R`. 

However, with the new template structure, `main.r` is hidden. Should we be encouraging users to run `faas build` and then find the `main.r` file in the `build` folder?

**Comment by onlyjsmith** [comment]
For function builders, I think the answer is 'yes'.

There's also `faas build --shrinkwrap` which is probably more useful - this doesn't build a container image, just creates the `build` folder. Great for testing if you've got all the dependencies installed on your machine already - which is likely for a builder. We mention it on [this page](https://docs.disarm.io/api-docs/disarm-algorithms-and-openfaas) but it's not very clear.

Think the change to make is on https://docs.disarm.io/api-docs/creating-and-deploying-functions/creating_in_r and https://docs.disarm.io/api-docs/creating-and-deploying-functions/creating_in_python pages.

**Comment by HughSt** [comment]
OK I think that makes sense. I think we just need to make sure users understand where the `main.r` or `index.py` files are once you run `faas build --shrinkwrap`. Is there anything else?

**Comment by onlyjsmith** [comment]
Have updated both Python and R in commit 35dd69b555f51508a57ca74341552ff6546d6b62
